"""Core runtime configuration for FSW."""

from __future__ import annotations


# GPIO map
BURNWIRE_GPIO = 20
EGG_SOLENOID_GPIO = 6
PARAFOIL_RIGHT_GPIO = 12
PARAFOIL_LEFT_GPIO = 13
# GNSS 7 Click RST (active low; pulse at GPS app startup unless GNSS_RESET_ENABLE=0)
GNSS_RESET_GPIO = 26

# Egg drop (flight state 4): rangefinder reading must be in
# [rough validity floor .. EGG_STATE_DISTANCE_TRIGGER_MM] to arm solenoid pulses.
# Typical: trigger when distance to ground <= 2500 mm with TF-Luna.
EGG_STATE_DISTANCE_TRIGGER_MM = 2500

# Relay logic levels (numeric for platform-agnostic GPIO compatibility)
# Base polarity is active-low relay modules: ON=0, OFF=1.
RELAY_ACTIVATE_LEVEL = 0
RELAY_DEACTIVATE_LEVEL = 1

# Per-actuator relay polarity
# - Release relay is wired opposite to the base polarity.
# - Egg relay follows the base polarity.
RELEASE_RELAY_ACTIVATE_LEVEL = RELAY_DEACTIVATE_LEVEL
RELEASE_RELAY_DEACTIVATE_LEVEL = RELAY_ACTIVATE_LEVEL
EGG_RELAY_ACTIVATE_LEVEL = RELAY_DEACTIVATE_LEVEL
EGG_RELAY_DEACTIVATE_LEVEL = RELAY_ACTIVATE_LEVEL


# Sensor/IO rates (Hz)
BAROMETER_RATE_HZ = 10
IMU_RATE_HZ = 50
GPS_RATE_HZ = 10
MOTOR_RATE_HZ = 20
ELECTRO_RATE_HZ = 1
DISTANCE_RATE_HZ = 10
XBEE_RATE_HZ = 10
CAMERA_FPS = 30


# GPS sanity gates.  Defaults are for the current Korea test area; update these
# before operating at a distant site.
GPS_EXPECTED_LON_CENTER_DEG = 126.6
GPS_EXPECTED_LON_RADIUS_DEG = 20.0
GPS_MIN_SATS = 4
GPS_MAX_VALID_SPEED_MPS = 40.0


# Release timing tuning
RELEASE_TARGET_RATIO = 0.8  # 80% max_alt: separation altitude target
# Below this fraction of max_alt: start descent-rate history and the FORCE_90PCT_TIMEOUT timer.
RELEASE_PREDICT_START_RATIO = 0.9
RELEASE_HARD_TRIGGER_RATIO = 0.85  # hard fallback if prediction is not viable
RELEASE_BURNWIRE_DELAY_SEC = 10.0 # 기존 5초, 0519 ETD 때 10초로 늘림. 5초는 너무 짧아서 낙하산이 완전히 펴지기도 전에 타버리는 경우가 있었음.
RELEASE_PREDICT_TIME_MIN_SEC = 0.0
RELEASE_PREDICT_TIME_MAX_SEC = 5.0
RELEASE_FORCE_AFTER_SEC = 5.0  # seconds after band crossing before FORCE_90PCT_TIMEOUT


# Motor guidance/control string constants
SENSOR_QUALITY_FRESH = "FRESH"
SENSOR_QUALITY_STALE = "STALE"

CONTROL_MODE_NOMINAL_CLOSED_LOOP = "NOMINAL_CLOSED_LOOP"
CONTROL_MODE_NOMINAL_FEEDFORWARD = "NOMINAL_FEEDFORWARD"
CONTROL_MODE_DEGRADED_CLOSED_LOOP = "DEGRADED_CLOSED_LOOP"
CONTROL_MODE_DEGRADED_FEEDFORWARD = "DEGRADED_FEEDFORWARD"
CONTROL_MODE_FAIL = "FAIL"

FAIL_REASON_NONE = "NONE"
FAIL_REASON_FREEFALL = "FREEFALL"
FAIL_REASON_TUMBLE_YAW_DOMINANT = "TUMBLE_YAW_DOMINANT"
FAIL_REASON_TUMBLE_ROLLPITCH = "TUMBLE_ROLLPITCH"
FAIL_REASON_UNSTABLE_BODY = "UNSTABLE_BODY"
FAIL_REASON_NO_POSITION = "NO_POSITION"
FAIL_REASON_NO_MOTION = "NO_MOTION"
FAIL_REASON_SENSOR_BLACKOUT = "SENSOR_BLACKOUT"

MOTOR_REASON_INIT = "INIT"
MOTOR_REASON_IDLE = "IDLE"
MOTOR_REASON_LANDED = "LANDED"
MOTOR_REASON_GUIDANCE_INACTIVE = "GUIDANCE_INACTIVE"
MOTOR_REASON_DISABLED = "DISABLED"
MOTOR_REASON_ACTIVE = "ACTIVE"
MOTOR_REASON_DEGRADED = "DEGRADED"
MOTOR_REASON_MANUAL_PREFIX = "MANUAL_"
MOTOR_MANUAL_LEFT = "LEFT"
MOTOR_MANUAL_NEUTRAL = "NEUTRAL"
MOTOR_MANUAL_RIGHT = "RIGHT"

CTRL_MODE_NEUTRAL = "NEUTRAL"
CTRL_MODE_CLOSED_LOOP = "CLOSED_LOOP"
CTRL_MODE_FEEDFORWARD_ONLY = "FEEDFORWARD_ONLY"
CTRL_MODE_GUIDANCE_TIMEOUT = "GUIDANCE_TIMEOUT"

CTRL_FALLBACK_NONE = "NONE"
CTRL_FALLBACK_GUIDANCE_TIMEOUT = "GUIDANCE_TIMEOUT"
CTRL_FALLBACK_GUIDANCE_ATTENUATED = "GUIDANCE_ATTENUATED"
CTRL_FALLBACK_GYRO_SPIKE = "GYRO_SPIKE"


# Motor guidance/control initial policy parameters
MOTOR_NOMINAL_CLOSED_LOOP_CONFIDENCE_SCALE = 1.0
MOTOR_NOMINAL_CLOSED_LOOP_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 32.0
MOTOR_NOMINAL_CLOSED_LOOP_LAT_ACC_MAX_MPS2 = 2.5
MOTOR_NOMINAL_CLOSED_LOOP_DELTA_FF_MAX_DEG = 80.0
MOTOR_NOMINAL_CLOSED_LOOP_DELTA_PID_MAX_DEG = 25.0
MOTOR_NOMINAL_CLOSED_LOOP_DELTA_TOTAL_MAX_DEG = 100.0
MOTOR_NOMINAL_CLOSED_LOOP_MAX_ARM_RATE_DEG_S = 60.0

MOTOR_NOMINAL_FEEDFORWARD_CONFIDENCE_SCALE = 1.0
MOTOR_NOMINAL_FEEDFORWARD_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 28.0
MOTOR_NOMINAL_FEEDFORWARD_LAT_ACC_MAX_MPS2 = 2.2
MOTOR_NOMINAL_FEEDFORWARD_DELTA_FF_MAX_DEG = 70.0
MOTOR_NOMINAL_FEEDFORWARD_DELTA_PID_MAX_DEG = 0.0
MOTOR_NOMINAL_FEEDFORWARD_DELTA_TOTAL_MAX_DEG = 85.0
MOTOR_NOMINAL_FEEDFORWARD_MAX_ARM_RATE_DEG_S = 55.0

MOTOR_DEGRADED_CLOSED_LOOP_CONFIDENCE_SCALE = 0.5
MOTOR_DEGRADED_CLOSED_LOOP_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 22.0
MOTOR_DEGRADED_CLOSED_LOOP_LAT_ACC_MAX_MPS2 = 1.6
MOTOR_DEGRADED_CLOSED_LOOP_DELTA_FF_MAX_DEG = 55.0
MOTOR_DEGRADED_CLOSED_LOOP_DELTA_PID_MAX_DEG = 20.0
MOTOR_DEGRADED_CLOSED_LOOP_DELTA_TOTAL_MAX_DEG = 75.0
MOTOR_DEGRADED_CLOSED_LOOP_MAX_ARM_RATE_DEG_S = 45.0

MOTOR_DEGRADED_FEEDFORWARD_CONFIDENCE_SCALE = 0.35
MOTOR_DEGRADED_FEEDFORWARD_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 18.0
MOTOR_DEGRADED_FEEDFORWARD_LAT_ACC_MAX_MPS2 = 1.2
MOTOR_DEGRADED_FEEDFORWARD_DELTA_FF_MAX_DEG = 45.0
MOTOR_DEGRADED_FEEDFORWARD_DELTA_PID_MAX_DEG = 0.0
MOTOR_DEGRADED_FEEDFORWARD_DELTA_TOTAL_MAX_DEG = 55.0
MOTOR_DEGRADED_FEEDFORWARD_MAX_ARM_RATE_DEG_S = 40.0

MOTOR_TUMBLE_YAW_DOMINANT_MIN_DEG_S = 80.0
MOTOR_TUMBLE_YAW_DOMINANT_RATIO = 1.5
MOTOR_TUMBLE_ROLLPITCH_MIN_DEG_S = 120.0
MOTOR_TUMBLE_COUNTER_YAW_GAIN = 0.5
MOTOR_TUMBLE_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 25.0
MOTOR_TUMBLE_DELTA_FF_MAX_DEG = 50.0
MOTOR_TUMBLE_DELTA_TOTAL_MAX_DEG = 60.0
MOTOR_TUMBLE_MAX_ARM_RATE_DEG_S = 50.0

MOTOR_TARGET_BEARING_GAIN = 1.0
MOTOR_TARGET_BEARING_ANGULAR_VELOCITY_CMD_MAX_DEG_S = 18.0
MOTOR_TARGET_BEARING_DELTA_FF_MAX_DEG = 45.0
MOTOR_TARGET_BEARING_DELTA_TOTAL_MAX_DEG = 55.0


# ── New GNC control mode string constants ─────────────────────────────────────
CONTROL_MODE_GPS_TRACKING_CLOSED = "GPS_TRACKING_CLOSED"
CONTROL_MODE_GPS_TRACKING_OPEN   = "GPS_TRACKING_OPEN"
CONTROL_MODE_DR_TRACKING_CLOSED  = "DR_TRACKING_CLOSED"
CONTROL_MODE_DR_TRACKING_OPEN    = "DR_TRACKING_OPEN"
CONTROL_MODE_DETUMBLING          = "DETUMBLING"

# Dead-reckoning method string constants
DR_METHOD_NONE                   = "NONE"
DR_METHOD_GYRO_INTEGRATION       = "GYRO_INTEGRATION"
DR_METHOD_ACC_DOUBLE_INTEGRATION = "ACC_DOUBLE_INTEGRATION"
DR_METHOD_GYRO_ACC_BLEND         = "GYRO_ACC_BLEND"

# ── L1 homing guidance tuning ─────────────────────────────────────────────────
L_GAIN_M  = 12.0
V_MIN_MPS = 0.5
V_MAX_MPS = 15.0

# ── Sensor freshness thresholds ───────────────────────────────────────────────
GPS_CONTROL_FRESH_MAX_AGE_S = 1.0
GPS_CORRECTION_MAX_AGE_S    = 2.0
IMU_FRESH_MAX_AGE_S         = 0.8
BARO_FRESH_MAX_AGE_S        = 0.8

HISTORY_WINDOW_S  = 8.0
SPEED_DECAY_TAU_S = 10.0

# ── Accelerometer-aided DR ────────────────────────────────────────────────────
USE_ACC_DOUBLE_INTEGRATION = True
ACC_AID_START_AGE_S        = 0.0
ACC_AID_END_AGE_S          = 5.0
ACC_LIMIT_MPS2             = 1.5
ACC_BLEND_WEIGHT           = 0.2

# ── DR confidence breakpoints ─────────────────────────────────────────────────
DR_CONF_AGE_1_S = 2.0
DR_CONF_AGE_2_S = 5.0
DR_CONF_AGE_3_S = 8.0

TARGET_RADIUS_M = 5.0

# ── Yaw rate limits per control mode (deg/s) ──────────────────────────────────
GPS_TRACKING_CLOSED_YAW_RATE_LIMIT_DPS = 35.0
GPS_TRACKING_OPEN_YAW_RATE_LIMIT_DPS   = 25.0
DR_TRACKING_CLOSED_YAW_RATE_LIMIT_DPS  = 20.0
DR_TRACKING_OPEN_YAW_RATE_LIMIT_DPS    = 12.0
DETUMBLING_YAW_RATE_LIMIT_DPS          = 0.0
FAIL_YAW_RATE_LIMIT_DPS                = 0.0

# ── Detumbling ────────────────────────────────────────────────────────────────
DETUMBLE_ENABLE             = True
DETUMBLE_GYRZ_THRESHOLD_DPS = 120.0
DETUMBLE_EXIT_THRESHOLD_DPS = 40.0
DETUMBLE_EXIT_HOLD_S        = 0.5

# ── Sensor sign conventions ───────────────────────────────────────────────────
GYRZ_SIGN      = 1.0
MOTOR_CMD_SIGN = 1.0
ACC_X_SIGN     = 1.0
ACC_Y_SIGN     = 1.0

# ── Yaw-rate controller gains ─────────────────────────────────────────────────
KFF_GPS_CLOSED = 0.0
KP_GPS_CLOSED  = 0.25   # matches existing ControlConfig.K_P

KFF_DR_CLOSED  = 0.0
KP_DR_CLOSED   = 0.15

KFF_GPS_OPEN = 0.10
KFF_DR_OPEN  = 0.05

KP_DETUMBLE = 0.10

KI_YAW_RATE = 0.0
KD_YAW_RATE = 0.0
