"""Core runtime configuration for FSW."""

from __future__ import annotations


# GPIO map
BURNWIRE_GPIO = 5
EGG_SOLENOID_GPIO = 6
PARAFOIL_RIGHT_GPIO = 12
PARAFOIL_LEFT_GPIO = 13


# Relay active level (keep numeric for platform-agnostic compatibility)
RELAY_ACTIVATE_LEVEL = 1
RELAY_DEACTIVATE_LEVEL = 0


# Sensor/IO rates (Hz)
BAROMETER_RATE_HZ = 10
IMU_RATE_HZ = 10
GPS_RATE_HZ = 20
MOTOR_RATE_HZ = 20
ELECTRO_RATE_HZ = 1
DISTANCE_RATE_HZ = 10
XBEE_RATE_HZ = 10
CAMERA_FPS = 30


# Release timing tuning
RELEASE_TARGET_RATIO = 0.8
RELEASE_PREDICT_START_RATIO = 0.9
RELEASE_HARD_TRIGGER_RATIO = 0.85
RELEASE_BURNWIRE_DELAY_SEC = 3.0
