import sys
from ui import GCS_Script
from PyQt6 import QtWidgets, uic
from PyQt6.QtGui import QFont, QResizeEvent, QFontMetrics
from PyQt6.QtCore import Qt
import time
import threading
import re

import serial.tools.list_ports

class MainWindow(QtWidgets.QMainWindow, GCS_Script.Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        
        # Do not change, automatically generated by QT studio
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        
        # Set window Title
        self.setWindowTitle("CANSAT 2025 Command Generator")
        
        # Set status Bar
        self.statusbar.showMessage("Idle...")
        
        self.deviceID = 1070

        self.logstr = ""
        self.textEdit_Logs.setText(self.logstr)
        self.textEdit_Logs.setReadOnly(True)

        # Flags
        self.updatingCmdHdrText = False
        self.updatingPayloadText = False
        
        # Setup the font for Command Editor
        self.CommandHeader_Font = QFont("Arial", 40)
        self.CommandHeader_Font.setBold(True)
        
        self.Payload_Font = QFont("Arial", 40)
        self.Payload_Font.setBold(True)
        
        # Allign the text to be in center
        self.textEdit_CommandHeader.setAlignment(Qt.AlignmentFlag.AlignVCenter)
        
        # Set the font
        self.textEdit_CommandHeader.setFont(self.CommandHeader_Font)
        
        # Connect the button to send command method
        self.pushButton_SendCommand.clicked.connect(self.send_command)
        
        # Refresh Ports
        self.refresh_ports()
        
        # Connect the Refresh Port button to refresh port
        self.pushButton_RefreshPorts.clicked.connect(self.refresh_ports)
        
        # Connect the port connect button
        self.pushButton_ConnectToPort.clicked.connect(self.connect_to_port)
        
        # Initial Port Status is Disconnected
        self.label_ConnectionStatus.setText("Disconnected")
        
        # Make Baud Rate Combobox
        baudrate_list = [4800, 9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600] #List of common baud rates
        baudrate_str_list = [str(x) for x in baudrate_list]
        
        self.comboBox_selectBaud.clear()
        self.comboBox_selectBaud.addItems(baudrate_str_list)
        self.comboBox_selectBaud.setCurrentIndex(1)

        # Initialize Serial
        self.CurrentSerialPort = serial.Serial()
        
        # Flag that indicates command is valid
        self.IsCommandValid = True
        
        self.pushButton_RefreshCommandList.clicked.connect(self.refresh_command_list)
        
        self.command_to_send = ""
        self.custom_command_str = ""

        self.command_list = []

        self.main_command_index = -1
        self.command_option_index = -1
        self.enable_custom_command = False

        self.simp_file_path = ""
        
        self.refresh_command_list()

        self.listWidget_CommandList.itemClicked.connect(self.load_from_selected_command)
        self.listWidget_CommandOption.itemClicked.connect(self.load_from_selected_option)
        self.textEdit_CustomCommand.textChanged.connect(self.on_custom_command_input)

        self.pushButton_RefreshLog.clicked.connect(self.refresh_log)
        self.pushButton_SelectFile.clicked.connect(self.select_file)

        # TCP Connection
        self.server_socket = None
        self.client_socket = None

        # Default port Selection is 12345
        self.tcpport = 12345
        self.spinBox_PortNum.setValue(self.tcpport)
        self.spinBox_PortNum.valueChanged.connect(self.ChangePortNum)
        self.pushButton_ConnectToSerialStudio.clicked.connect(self.ConnectToSerialStudio)
        self.pushButton_DisconnectSerialStudio.clicked.connect(self.DisconnectSerialStudio)

        self.device_list = []
        self.refresh_device_list()
        self.listWidget_SelectDevice.itemClicked.connect(self.load_from_selected_device)
        self.listWidget_SelectDevice.setCurrentRow(0)

        self.pushButton_RefreshDeviceList.clicked.connect(self.refresh_device_list)
        
        self.pushButton_SendSIMP.clicked.connect(self.send_simp_data)
        self.pushButton_StopSIMP.clicked.connect(self.stop_simp_data)

        self.current_device_index = 0

    def select_file(self):
        self.simp_file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self, "Select File","",
            "CSV Files (*.csv);;All Files (*)",
            )
        if self.simp_file_path:
            self.label_SIMP_filepath.setText(self.simp_file_path)
        else:
            self.label_SIMP_filepath.setText("No file selected")

    def add_log_entry(self, log_entry):
        self.logstr = f"{log_entry}\n{self.logstr}"
        self.textEdit_Logs.setText(self.logstr)
        return
    
    def refresh_log(self):
        self.logstr = ""
        self.textEdit_Logs.setText(self.logstr)
        return

    def update_command_text(self):
        self.command_to_send = f"CMD,{self.deviceID},"

        # Add main command
        if self.main_command_index != -1:
            self.command_to_send += f"{self.command_list[self.main_command_index][1]}"

        # Add option
        if self.command_option_index != -1:
            if self.enable_custom_command == False:
                self.command_to_send += f",{self.command_list[self.main_command_index][2][self.command_option_index][1]}"
            else:
                self.command_to_send += f",{self.custom_command_str}"
        
        # Add Endline
        self.command_to_send += "\n"

        self.textEdit_CommandHeader.setText(self.command_to_send)

        return
    
    def load_from_selected_command(self, item):
        self.textEdit_CommandHeader.clear()

        self.main_command_index = self.listWidget_CommandList.indexFromItem(item).row()

        self.command_option_index = -1

        self.listWidget_CommandOption.clear()
        for option in self.command_list[self.main_command_index][2]:
            self.listWidget_CommandOption.addItem(option[0])
        
        self.update_command_text()
        return

    def load_from_selected_option(self, item):
        self.textEdit_CommandHeader.clear()

        self.command_option_index = self.listWidget_CommandOption.indexFromItem(item).row()

        if self.command_list[self.main_command_index][2][self.command_option_index][1] == "[]":
            self.enable_custom_command = True
        
        else:
            self.enable_custom_command = False
        
        self.update_command_text()
        return

    def on_custom_command_input(self):
        self.custom_command_str = self.textEdit_CustomCommand.toPlainText()
        self.update_command_text()

        return

    def refresh_command_list(self):
        # Read the command list from a file
        try:
            with open("./commands/command_list.txt", "r") as file:
                file_lines = file.readlines()
                self.command_list.clear()
                
                ignore_line = False

                for line in file_lines:
                    line_to_read = line.strip()
                    if line_to_read == "###":
                        ignore_line = not ignore_line
                        continue

                    if ignore_line:
                        continue
                    
                    if line_to_read == "\n" or not line_to_read:
                        continue

                    splitted_line = line_to_read.split("/")

                    Main_Command_Name , Main_Command_Cmd = splitted_line[0].split(":")
                    Main_Command_Name = Main_Command_Name.strip()
                    Main_Command_Cmd = Main_Command_Cmd.strip()

                    option_list = []

                    if len(splitted_line) >= 2 : 
                        Options = splitted_line[1]

                        Option_list = Options.split("|")
                        for option in Option_list:
                            option_name, option_command = option.split(":")
                            option_name = option_name.strip()
                            option_command = option_command.strip()

                            option_list.append([option_name, option_command])

                    self.command_list.append([Main_Command_Name, Main_Command_Cmd, option_list])
                
                self.listWidget_CommandList.clear()
                self.listWidget_CommandOption.clear()
                self.textEdit_CustomCommand.clear()

                for command in self.command_list:
                    self.listWidget_CommandList.addItem(command[0])
            self.main_command_index = -1
            self.command_option_index = -1
            
            self.update_command_text()
            self.print_on_statusbar(f"refreshed command list")

        except Exception as e:
            print("Error reading command list:", e)

    def refresh_device_list(self):
# Read the command list from a file
        try:
            with open("./commands/device_list.txt", "r") as file:
                file_lines = file.readlines()
                self.device_list.clear()
                self.listWidget_SelectDevice.clear()

                ignore_line = False

                for line in file_lines:
                    line_to_read = line.strip().replace(" ", "")
                    if line_to_read == "###":
                        ignore_line = not ignore_line
                        continue

                    if ignore_line:
                        continue
                    
                    if line_to_read == "\n" or not line_to_read:
                        continue

                    splitted_line = line_to_read.split(":")
                    splitted_line[1] = int(splitted_line[1])
                    self.device_list.append(splitted_line)

                for device in self.device_list:
                    self.listWidget_SelectDevice.addItem(device[0])
                
                self.print_on_statusbar(f"refreshed device list")

        except Exception as e:
            print("Error reading device list:", e)
        return
    
    def load_from_selected_device(self, item):
        self.textEdit_CommandHeader.clear()
        self.current_device_index = self.listWidget_SelectDevice.indexFromItem(item).row()
        self.deviceID = self.device_list[self.current_device_index][1]
        self.update_command_text()

    def refresh_ports(self):
        ## Get lists of serial port
        ports = serial.tools.list_ports.comports()
        port_list = [f"{port.device}" for port in ports]
        print(port_list)
        self.print_on_statusbar(f"refreshed port list : {port_list}")
        self.comboBox_selectPort.clear()
        # Add the ports to ComboBox
        self.comboBox_selectPort.addItems(port_list)
        
    def connect_to_port(self):
        selected_port = self.comboBox_selectPort.currentText()
        selected_baud = int(self.comboBox_selectBaud.currentText())
        try:
            if self.CurrentSerialPort.is_open:
                self.CurrentSerialPort.close()
            self.CurrentSerialPort = serial.Serial(selected_port, selected_baud)
            print(self.CurrentSerialPort)
        except Exception as e:
            self.print_on_statusbar(f"Error during connection : {e}")

        self.label_ConnectionStatus.setText(f"Connected : {self.CurrentSerialPort.name}")

        text_to_log = f"Connected to port {self.CurrentSerialPort.name}"
        self.print_on_statusbar(text_to_log)
        
    def send_command(self):
        if self.IsCommandValid == False:
            self.print_on_statusbar("Command is Not Valid")
            return
        
        bytes_to_send = self.command_to_send.encode()
    
        if self.CurrentSerialPort.is_open:
            self.CurrentSerialPort.write(bytes_to_send)
            self.print_on_statusbar(f"Sent Command : {bytes_to_send.hex()}")
        else:
            self.print_on_statusbar("Port not opened!")
        
    def print_on_statusbar(self, str_to_print):
        current_time = time.strftime("%H:%M:%S")
        str_to_print = f"{current_time} : {str_to_print}"

        self.statusbar.showMessage(str_to_print)
        self.add_log_entry(str_to_print)
    
    def ConnectToSerialStudio(self):

        self.spinBox_PortNum.isEnabled = False

        # If server socket exists
        if self.server_socket != None:
            self.print_on_statusbar(f"Error! Server socket exists, terminate server before reconnecting!")
            return
        
        # If serial port exists
        if not self.CurrentSerialPort.is_open:
            self.print_on_statusbar(f"Error! Open serial port before connecting to serial studio!")
            return
        
        self.server_socket, self.client_socket = handling_server.start_tcp_server(self.tcpport)
        self.label_SerialStudioConnection.setText("Connecting...")

        if self.client_socket == None:
            self.label_SerialStudioConnection.setText("Connection Timeout")
            self.print_on_statusbar(f"Error! Connection Timeout!")
            return
        
        threading.Thread(target=handling_server.sensor_data_receiver, args=(self.CurrentSerialPort, self.client_socket,), daemon=True, name="CommandRouter").start()
        self.label_SerialStudioConnection.setText(f"Connected to serial studio at port {self.tcpport}")
    
    def DisconnectSerialStudio(self):
        handling_server.terminate_connection(self.client_socket)
        handling_server.terminate_server_socket(self.server_socket)

        self.client_socket = None
        self.server_socket = None

        self.label_ConnectionStatus = "Disconnected"

        self.print_on_statusbar("Serial Studio disconnected")

        self.spinBox_PortNum.isEnabled = True

    def ChangePortNum(self):
        self.tcpport = self.spinBox_PortNum.value()
    
    def send_simp_data(self):
        if not self.CurrentSerialPort.is_open:
            self.print_on_statusbar("Error starting SIMP thread, open serial port first!")        
            return
        
        handling_server.issendingsimpdata = True
        print("Starting Send simp data thread ...")
        threading.Thread(target=handling_server.simp_data_sender_thread, args=(self.CurrentSerialPort, self.simp_file_path, self.deviceID, )).start()

    def stop_simp_data(self):
        handling_server.issendingsimpdata = False
        self.print_on_statusbar("Stopped sending SIMP Data")        

    def resizeEvent(self, event: QResizeEvent) -> None:
        super().resizeEvent(event)
            
from scripts import handling_server

TCP_SERVER_OPEN = False

try:
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec()
    
except Exception as e:
    print("Error Running Program : ", e)
    app.quit()